/*
CREATE DATABASE enc_mal_tra
*/

CREATE TABLE enc_mal_tra.temp_ztyk4h3v6s_1 (
    session INT,  -- 
    Flag_of_packets INT,  -- 
    Traffic_sequence BIGINT,  -- 
    -- FIXME: how to set data type DOUBLE
    Payload_ratio DOUBLE,  -- 
    Length_of_IP_packets INT,  -- 
    Length_of_TCP_payload INT,  -- 
    Length_of_TCP_packet_header INT,  -- 
    Length_of_IP_packet_header INT,  -- 
    TCP_windows_size_value INT,  -- 
    Length_of_TCP_segment_packet INT,  -- 
    Time_difference_between_packets_per_session INT,  -- 
    Change_values_of_TCP_windows_length_per_session INT,  -- 
    Interval_of_arrival_time_of_forward_traffic INT,  -- 
    Interval_of_arrival_time_of_backward_traffic INT,  -- 
    Time_to_live INT,  -- 
    Ratio_to_previous_packets_in_each_session INT,  -- 
    Total_length_of_IP_packet_per_session INT,  -- 
    Total_Time_to_live_per_session INT,  -- 
    The_times_of_change_of_TCP_windows_length INT,  -- 
    The_times_of_change_of_payload_per_session INT,  -- 
    Total_length_of_forward_payload INT,  -- 
    Total_length_of_backward_payload INT,  -- 
    Total_length_of_forward_IP_header INT,  -- 
    Total_length_of_backward_IP_header INT,  -- 
    Total_length_of_forward_TCP_header INT,  -- 
    Total_length_of_backward_TCP_header INT,  -- 
    Total_length_of_forward_IP_packets INT,  -- 
    Total_length_of_backward_IP_packets INT,  -- 
    flow_duration INT,  -- 
    Packets_From_Clients INT,  -- 
    Packets_From_Servers INT,  -- 
    Bytes_From_Clients_IPpacket INT,  -- 
    Bytes_From_Servers_IPpacket INT,  -- 
    mean_Length_of_IP_packets INT,  -- 
    median_Length_of_IP_packets INT,  -- 
    max_Length_of_IP_packets INT,  -- 
    min_Length_of_IP_packets INT,  -- 
    std_Length_of_IP_packets INT,  -- 
    var_Length_of_IP_packets INT,  -- 
    mean_Length_of_TCP_payload INT,  -- 
    median_Length_of_TCP_payload INT,  -- 
    max_Length_of_TCP_payload INT,  -- 
    min_Length_of_TCP_payload INT,  -- 
    std_Length_of_TCP_payload INT,  -- 
    var_Length_of_TCP_payload INT,  -- 
    mean_Length_of_TCP_packet_header INT,  -- 
    median_Length_of_TCP_packet_header INT,  -- 
    max_Length_of_TCP_packet_header INT,  -- 
    min_Length_of_TCP_packet_header INT,  -- 
    std_Length_of_TCP_packet_header INT,  -- 
    var_Length_of_TCP_packet_header INT,  -- 
    mean_Length_of_IP_packet_header INT,  -- 
    median_Length_of_IP_packet_header INT,  -- 
    max_Length_of_IP_packet_header INT,  -- 
    min_Length_of_IP_packet_header INT,  -- 
    std_Length_of_IP_packet_header INT,  -- 
    var_Length_of_IP_packet_header INT,  -- 
    mean_TCP_windows_size_value INT,  -- 
    median_TCP_windows_size_value INT,  -- 
    max_TCP_windows_size_value INT,  -- 
    min_TCP_windows_size_value INT,  -- 
    std_TCP_windows_size_value INT,  -- 
    var_TCP_windows_size_value INT,  -- 
    mean_Length_of_TCP_segment_packet INT,  -- 
    median_Length_of_TCP_segment_packet INT,  -- 
    max_Length_of_TCP_segment_packet INT,  -- 
    min_Length_of_TCP_segment_packet INT,  -- 
    std_Length_of_TCP_segment_packet INT,  -- 
    var_Length_of_TCP_segment_packet INT,  -- 
    mean_Time_difference_between_packets_per_session INT,  -- 
    median_Time_difference_between_packets_per_session INT,  -- 
    max_Time_difference_between_packets_per_session INT,  -- 
    min_Time_difference_between_packets_per_session INT,  -- 
    std_Time_difference_between_packets_per_session INT,  -- 
    var_Time_difference_between_packets_per_session INT,  -- 
    mean_Change_values_of_TCP_windows_length_per_session INT,  -- 
    median_Change_values_of_TCP_windows_length_per_session INT,  -- 
    max_Change_values_of_TCP_windows_length_per_session INT,  -- 
    min_Change_values_of_TCP_windows_length_per_session INT,  -- 
    std_Change_values_of_TCP_windows_length_per_session INT,  -- 
    var_Change_values_of_TCP_windows_length_per_session INT,  -- 
    mean_Interval_of_arrival_time_of_forward_traffic INT,  -- 
    median_Interval_of_arrival_time_of_forward_traffic INT,  -- 
    max_Interval_of_arrival_time_of_forward_traffic INT,  -- 
    min_Interval_of_arrival_time_of_forward_traffic INT,  -- 
    std_Interval_of_arrival_time_of_forward_traffic INT,  -- 
    var_Interval_of_arrival_time_of_forward_traffic INT,  -- 
    mean_Interval_of_arrival_time_of_backward_traffic INT,  -- 
    median_Interval_of_arrival_time_of_backward_traffic INT,  -- 
    max_Interval_of_arrival_time_of_backward_traffic INT,  -- 
    min_Interval_of_arrival_time_of_backward_traffic INT,  -- 
    std_Interval_of_arrival_time_of_backward_traffic INT,  -- 
    var_Interval_of_arrival_time_of_backward_traffic INT,  -- 
    mean_time_to_live INT,  -- 
    median_time_to_live INT,  -- 
    max_time_to_live INT,  -- 
    min_time_to_live INT,  -- 
    std_time_to_live INT,  -- 
    var_time_to_live INT,  -- 
    label INT,  -- 
    Destination_port INT,  -- 
    Source_port INT,  -- 
    std_forward_pkt_length INT,  -- 
    std_backward_pkt_length INT,  -- 
    duration_forward INT,  -- 
    duration_back INT,  -- 
    mean_of_backward_IP_header INT,  -- 
    mean_of_forward_IP_header INT,  -- 
    total_payload_per_session INT,  -- 
    IPratio INT,  -- 
    Goodput INT,  -- 
    source_IP_address INT,  -- 
    Destination_IP_address INT  -- 
)
